databases:
  bronze:
    comment: "The Bronze Layer is where we land all the data from external source systems. The table structures in this layer correspond to the source system table structures 'as-is,' along with any additional metadata columns that capture the load date/time, process ID, etc."
    roles: ["R","RW"]
  silver:
    comment: "The Silver layer is where we apply standardisation to our source datasets. This standardisation aligns field names across sources, applies common data cleaning operations and organises the data into a well known structure."
    roles: ["R","RW"]
  gold:
    comment: "The Gold layer is for reporting and uses more de-normalized and read-optimized data models with fewer joins. The final layer of data transformations and data quality rules are applied here."
    roles: ["R","RW"]
  operations:
    comment: "This database is designed to store dbt operation materialised data."
    roles: ["R","RW"]
  retl:
    comment: "This database is designed to store retl operations produced data."
    roles: ["R","RW"]

warehouses:
  transform:
    warehouse_size: SMALL
    comment: "The Transform Warehouse is used by external transformation tools. Unlike ingestion tools, these external tools may not have their own scalable functionality. Therefore, a burstable larger warehouse size might be required as demand increases."
    grantees: ["transform"]
  ingestion:
    warehouse_size: SMALL
    comment: "The Ingestion Warehouse is used by external ingestion tools and processes."
    grantees: ["ingestion"]
  reporting:
    warehouse_size: MEDIUM
    comment: "The Reporting Warehouse is used by external reporting and analytics tools and processes."
    grantees: ["reporting"]
  retl:
    warehouse_size: SMALL
    comment: "The rETL Warehouse is used by external tools and processes for rETL operations."
    grantees: []

technical_roles:
  transform:
    parent_role: SYSADMIN
    db_role_grants:
      - { db: operations, kind: RW }
      - { db: operations, kind: R }
      - { db: bronze,     kind: RW }
      - { db: bronze,     kind: R }
      - { db: silver,     kind: RW }
      - { db: silver,     kind: R }
      - { db: gold,       kind: RW }
      - { db: gold,       kind: R }
  ingestion:
    parent_role: SYSADMIN
    db_role_grants:
      - { db: bronze, kind: RW }
      - { db: bronze, kind: R }
  reporting:
    parent_role: SYSADMIN
    db_role_grants:
      - { db: gold, kind: R }
  retl:
    parent_role: SYSADMIN
    db_role_grants:
      - { db: gold, kind: R }

service_users:
  dbt:
    name_prefix: "DBT_SERVICE_USER"
    default_role_key: "transform"
    default_warehouse_key: "transform"
    default_database_key: "silver"
    default_secondary_roles_option: "ALL"
    technical_role_keys: ["transform"]

  dbt_operations:
    name_prefix: "DBT_SERVICE_USER_OPERATIONS"
    default_role_key: "transform"
    default_warehouse_key: "transform"
    default_database_key: "silver"
    default_secondary_roles_option: "ALL"
    technical_role_keys: ["transform"]

  fivetran:
    name_prefix: "FIVETRAN_SERVICE_USER"
    default_role_key: "ingestion"
    default_warehouse_key: "ingestion"
    default_database_key: "bronze"
    default_secondary_roles_option: "ALL"
    technical_role_keys: ["ingestion"]

  kafka:
    name_prefix: "KAFKA_SERVICE_USER"
    default_role_key: "ingestion"
    default_warehouse_key: "ingestion"
    default_database_key: "bronze"
    default_secondary_roles_option: "ALL"
    technical_role_keys: ["ingestion"]

  airflow:
    name_prefix: "AIRFLOW_SERVICE_USER"
    default_role_key: "ingestion"
    default_warehouse_key: "ingestion"
    default_database_key: "bronze"
    default_secondary_roles_option: "ALL"
    technical_role_keys: ["ingestion"]

  looker:
    name_prefix: "LOOKER_SERVICE_USER"
    default_role_key: "reporting"
    default_warehouse_key: "reporting"
    default_database_key: "gold"
    default_secondary_roles_option: "ALL"
    technical_role_keys: ["reporting"]

  growthbook:
    name_prefix: "GROWTHBOOK_SERVICE_USER"
    default_role_key: "reporting"
    default_warehouse_key: "reporting"
    default_database_key: "gold"
    default_secondary_roles_option: "ALL"
    technical_role_keys: ["reporting"]

tech_role_user_grants:
  DBT_USER: ["transform"]
